### ISSUE TITLE
Your forking strategy

### ISSUE THREAD

**Issue by ccoVeille** [Zxilly/Zxilly#2]
Hi Zxilly,

I'm using this repository to contact you.

I saw you started using an organization for forking

https://github.com/ZxillyFork

Could you share why?

I imagine it's for separating things and avoiding your Zxilly space to be filled with forks you do. But I'm curious

how easily does this integrate with GitHub cli ? Or git machete?

I like your idea, I consider doing as you did.

**Comment by ccoVeille** [comment]
@Zxilly

**Comment by Zxilly** [comment]
I created this organization mainly to serve my go project, the go module allows me to replace a package using the replace directive.

Generally I'll submit changes upstream to wait for a merge. However, if a project hasn't been maintained for a while, it may take long time to wait for reply. Or if it's obvious that my requirements will conflict with upstream.In these cases I'll choose to maintain my own copy in this organization.

I don't use automated tools to do this, it's done entirely manually using git.

**Comment by ccoVeille** [comment]
Thanks for replying and explaining it.

The idea of hacking the go.mod with replace is a good idea.
